import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArchive,
  IconArrowRight,
  IconBell,
  IconBold,
  IconBox,
  IconBrandGithub,
  IconBrandTwitter,
  IconBrightness,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconInfoCircle,
  IconItalic,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconRosetteDiscountCheck,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconWorld,
  IconBug,
  IconCrown,
  IconX,
  IconPlayerPlay,
  IconPlayerStop,
  IconWallet,
  IconHistory,
  IconChartBar,
  IconDroplet,
  IconShieldCheck,
  IconUserCheck,
  IconTruck,
  IconClipboardList,
  IconPackage,
  IconBrandWhatsapp,
  IconPrinter,
  IconFileSearch,
  IconDeviceFloppy,
  IconArrowLeft,
  IconEye,
  IconCurrencyDollar,
  IconWifi,
  IconDownload,
  IconBike,
  IconMessageCircle,
  IconQrcode,
  IconCamera,
  IconRefresh,
  IconLink,
  IconFileUpload,
  IconBuilding,
  IconHash,
  IconUserPlus,
  IconDeviceMobile,
  IconCar,
  IconCopy,
  IconRoute,
  IconGasStation,
  IconGauge,
  IconTool,
  IconKey,
  IconAppWindow,
  IconInbox,
  IconClipboardCheck,
  IconShieldExclamation,
  IconTicket,
  IconReceiptTax,
  IconCertificate,
  IconBuildingBank,
  IconCalendarTime,
  IconPlaneDeparture,
  IconFileCertificate,
  IconPin
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  logo: IconCommand,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,

  // Language
  language: IconWorld,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  plus: IconPlus,
  edit: IconEdit,
  upload: IconUpload,

  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Data / Charts
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  pizza: IconPizza,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots,

  // AAMS
  play: IconPlayerPlay,
  stop: IconPlayerStop,
  wallet: IconWallet,
  history: IconHistory,
  chartBar: IconChartBar,
  droplet: IconDroplet,
  shield: IconShieldCheck,
  userCheck: IconUserCheck,
  truck: IconTruck,
  clipboardList: IconClipboardList,
  inventory: IconPackage,
  employees: IconUsers,
  whatsapp: IconBrandWhatsapp,
  printer: IconPrinter,

  // AAMS (extra)
  fileSearch: IconFileSearch,
  save: IconDeviceFloppy,
  arrowLeft: IconArrowLeft,
  eye: IconEye,
  dollarSign: IconCurrencyDollar,
  wifi: IconWifi,
  download: IconDownload,
  bike: IconBike,
  messageCircle: IconMessageCircle,
  qrCode: IconQrcode,
  camera: IconCamera,
  refresh: IconRefresh,
  link: IconLink,
  fileUpload: IconFileUpload,
  building: IconBuilding,
  hash: IconHash,
  userPlus: IconUserPlus,
  smartphone: IconDeviceMobile,
  car: IconCar,
  copy: IconCopy,
  route: IconRoute,
  fuel: IconGasStation,
  gauge: IconGauge,
  tool: IconTool,
  wrench: IconTool,
  key: IconKey,
  appWindow: IconAppWindow,
  inbox: IconInbox,
  clipboardCheck: IconClipboardCheck,
  shieldAlert: IconShieldExclamation,
  fileText: IconFileText,
  globe: IconWorld,
  bug: IconBug,
  ticket: IconTicket,
  violation: IconReceiptTax,
  certificate: IconCertificate,
  bank: IconBuildingBank,
  leaves: IconPlaneDeparture,
  fileCertificate: IconFileCertificate,
  calendarTime: IconCalendarTime,
  receipt: IconReceiptTax,
  pin: IconPin,
  archive: IconArchive
};
